language: node_js
node_js:
  - "5"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
  - "5.9"
  - "5.10"
  - "4"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"